apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{.Chart.Name}}-deployment
spec:
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      containers:
      - name: {{.Chart.Name}}
        image: {{.Values.imageRegistry}}/{{.Chart.Name}}:{{.Chart.AppVersion}}
        ports:
        - name: http-server
          containerPort: {{.Values.containerPort}}
        env:
        - name: INFRA_ENV
          valueFrom:
            configMapKeyRef:
              name: env-vars-configmap
              key: INFRA_ENV
        - name: VERSION
          valueFrom:
            configMapKeyRef:
              name: env-vars-configmap
              key: VERSION
